apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo-roll-test-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/ingressgateway
  http:
    - name: primary
      route:
        - destination:
            host: argo-roll-test
            subset: old
          weight: 100
        - destination:
            host: argo-roll-test
            subset: new
          weight: 0
