apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ayoobkibrahim/argo-rollouts-project.git
    path: apps/ui/k8s/overlays/dev
    targetRevision: HEAD  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
